# Generated by Django 4.0.4 on 2022-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_print',
        ),
        migrations.AddField(
            model_name='book',
            name='appropriate',
            field=models.CharField(choices=[('Childrens', 'Under 8'), ('Young Adult', '8 - 15'), ('Adults Only', '15 and up')], default='adults only', max_length=15),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
