# Generated by Django 4.0.4 on 2022-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/static/books/images/default.jpg', upload_to='./static/books/images/'),
        ),
    ]
