version: 2.1

jobs:
  this_job_will_cause_error:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: cat ss
          
      - run:
          name: this will run when a job fail
          command: echo "job failed"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - this_job_will_cause_error