version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
         command: echo "hello from output.txt" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: alpine
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
workflows:
  default:
    jobs:
      - save_hello_world_output
