version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  save_hello_world_output:
    docker:
      - image: alpine
    steps:
      - print_pipeline_id

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output